@host=https://localhost:7146

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "email@example.com",
    "password": "password!"
}
