@host=https://localhost:7146

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstname": "firstname",
    "lastname": "lastname",
    "email": "esmail@example.com",
    "password": "password!22"
}
