@host=https://localhost:7146
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTdXJ2ZXlNYW5hZ2VyLkRvbWFpbi5TdXJ2ZXlBZ2dyZWdhdGUuVmFsdWVPYmplY3RzLlN1cnZleUlkIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiam9obi5kb2VAZXhhbXBsZS5jb20iLCJqdGkiOiJhM2E1NGZhYy1mM2QxLTRjODgtOGM1ZS0zNGNlZDM3ZjU4ZWEiLCJleHAiOjE2ODkxNTI0NzIsImlzcyI6IlN1cnZleU1hbmFnZXJBcHBJc3N1ZXIiLCJhdWQiOiJTdXJ2ZXlNYW5hZ2VyQXBwQXVkaWVuY2UifQ.Bt_qwBxd7yD7aTQzY0YEsvDGf7HTVKJ5xwn6HFc6oks
@hostId=00000000-0000-0000-0000-0000000000
GET {{host}}/hosts/{{hostId}}/surveys
Content-Type: application/json

