public record CreateAnswerRequest(
    Guid SurveyId,
    Guid HostId,
    List<AnswerRequest> Answers);

public record AnswerRequest(
    string QuestionName,
    string Type,
    List<string>? Answer
);


@host=https://localhost:7146
@surveyId=00000000-0000-0000-0000-0000000000

POST {{host}}/anonymsurveys/answers
Content-Type: application/json

{
    "surveyId": "00000000-0000-0000-0000-0000000000",
    "hostId": "00000000-0000-0000-0000-0000000000",
    "answers": [
        {
            "questionName": "name",
            "type": "text",
            "answer": ["Bu bir ankara havaısıdır"]
        },
        {
            "questionName": "quetionname",
            "type": "type",
            "answer": ["choice1", "choice2"]
        },
        {
            "questionName": "name",
            "type": "radio",
            "answer": ["5"]
        },
    ]
}