@host=https://localhost:7146

GET {{host}}/surveys
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNzFjOGU1My1mYWFjLTRjZDEtOTU0Mi1kNGZhYjA3ZGQ5YzgiLCJnaXZlbl9uYW1lIjoiZmlyc3QtbmFtZSIsImZhbWlseV9uYW1lIjoibGFzdC1uYW1lIiwiZW1haWwiOiJlbWFpbEBleGFtcGxlLmNvbSIsImp0aSI6IjYyOGM4MjVkLTc2ZmMtNGUwMy1iMjc5LTJmZTAxM2YwYTAyOSIsImV4cCI6MTY4NzYxMzExMSwiaXNzIjoiU3VydmV5TWFuYWdlckFwcElzc3VlciIsImF1ZCI6IlN1cnZleU1hbmFnZXJBcHBBdWRpZW5jZSJ9.Clop51Qtr_flkYW5lVuX53dRW9M7EwGn_mUmLVYIiFM