@host=https://localhost:7146

GET {{host}}/surveys
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwODMyNjcxNC00YjQ3LTQzMGEtYTlmMy1hMjYxNTY5NzE5NWEiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZW1haWwiOiJlbWFpbEBleGFtcGxlLmNvbSIsImp0aSI6IjhmZjVhOWNhLWNmOGEtNGQwNS04YjAxLTYyYmMxZDBlZTI5NyIsImV4cCI6MTY4NzY0OTg1MywiaXNzIjoiU3VydmV5TWFuYWdlckFwcElzc3VlciIsImF1ZCI6IlN1cnZleU1hbmFnZXJBcHBBdWRpZW5jZSJ9.-4BISambdFpeLADJe27ucByMyu9XJQe1q2LkL49RPeY
