@host=https://localhost:7146
@hostId=AA1CA5F7-D2D6-4759-BD64-AA86D9011964


GET {{host}}/hosts/{{hostId}}/surveys/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTdXJ2ZXlNYW5hZ2VyLkRvbWFpbi5TdXJ2ZXlBZ2dyZWdhdGUuVmFsdWVPYmplY3RzLlN1cnZleUlkIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImVtYWlsIjoiZW1haWxAZXhhbXBsZS5jb20iLCJqdGkiOiI4ZWQyMDVjNC1iMjI2LTRmNjQtOTM5My1mZGE3Y2EyOGYxMjUiLCJleHAiOjE2ODkwMzAzMjgsImlzcyI6IlN1cnZleU1hbmFnZXJBcHBJc3N1ZXIiLCJhdWQiOiJTdXJ2ZXlNYW5hZ2VyQXBwQXVkaWVuY2UifQ.W9qGe10AiUJhz1_c9-1q30texTzSr9pAp0NLn3_9RNg